### ISSUE TITLE
Removing logic to handle overlapping special districts

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-zoningtaxlots#101]
Remove the logic  to handle overlapping special districts. TRD has created a single special district polygon to handle these cases, e.g., "125th/TA"

**Comment by mgraber** [comment]
@AmandaDoyle  this logic?
https://github.com/NYCPlanning/db-zoningtaxlots/blob/0fdc2607b98acda830fb8c10e47b1b7bb6bafd31/sql/area_specialdistrict.sql#L64-L93

**Comment by AmandaDoyle** [comment]
@mgraber Yes.  That chuck of code can be commented out.
