### ISSUE TITLE
Adding MIH fields

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-zoningtaxlots#12]
MIH Flag
Yes (>10%), No (<10%)
Option
Which MIH option applies to the lot.

@croswell81 going to follow up with % thresholds for Flag , and include spatial data in zoning map package, but send version of data asap so that we can start developing

**Comment by SPTKL** [comment]
`mihflag` --> binary value
`mihoption` --> comes from shapefile

**Comment by AmandaDoyle** [comment]
@croswell81 we implemented 'area_mih.sql'

The way it's currently written `mihflag` is a binary value and assigned a value of `true` when 10% or more of a lot is covered by an MIH polygon, and then the `mihoption' field is populated accordingly.  

If this needs to be updated just let us know what the logic should be an we can easily update it
