### ISSUE TITLE
zon1 and zon2 fliped

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-zoningtaxlots#25]
Dockerized version qc_bbldiff table has 11 records of difference compare to the latest build (08312019)
observed issues: 
 - zon1 zon2 flipped (perfect 50% 50%, how to determine the right order?)
![image](https://user-images.githubusercontent.com/13207770/64554633-ced8ec80-d309-11e9-8c02-4289aeb3eb74.png)
- close to 10%, rounding issues
![image](https://user-images.githubusercontent.com/13207770/64554663-de583580-d309-11e9-9e2e-1786862af4d0.png)

**Comment by AmandaDoyle** [comment]
In cases where a lot is covered by the same amount of 2 zoning districts choose the leading district with the following order
Residential, Commercial, Manufacturing, Park 
If there is a case where there are two residential districts, for example, then list the districts in numerical ascending order (i.e. ZD1 = R3, ZD2 = R4)

**Comment by SPTKL** [comment]
```
WITH new_order AS(
  SELECT bbl, zonedist, ROW_NUMBER()
  OVER(PARTITION BY bbl
          ORDER BY priority ASC) AS row_number
    FROM (
      SELECT * FROM lotzoneperorder
      WHERE bbl in(SELECT bbl from(
        SELECT bbl, MAX(segbblgeom) - MIN(segbblgeom) as diff 
        FROM lotzoneperorder 
        WHERE perbblgeom >= 10
        group by bbl
      ) a WHERE diff > 0 and diff < 0.01))a 
      JOIN zonedist_priority 
      USING (zonedist))
UPDATE lotzoneperorder
SET row_number = new_order.row_number
FROM new_order
WHERE lotzoneperorder.bbl = new_order.bbl 
  AND lotzoneperorder.zonedist = new_order.zonedist; 
```
