### ISSUE TITLE
qaqc updates

### ISSUE THREAD

**Issue by SPTKL** [NYCPlanning/db-zoningtaxlots#26]
- [x] Combine qc_versioncomparison.csv with qc_versioncomparisonnownullcount.csv; sort by field name. (Resulting report will show if the value changed to a different value or to/from a null value).
- [x] Add a difference column to qc_frequencychanges.csv; sort by field name.
Add two fields to the BBL diff report
- [ ] Flag indicating that lot intersects with a rezoning done since the last version
- [ ] Flag indicating that the area of the lot (taken from DTM) has changed by more than +/- 10% since the last version
- [x] Rename fields in BBL diff report for the fields showing the new data, using similar naming convention as used for previous data set, e.g., ZD1NEW.

**Comment by AmandaDoyle** [comment]
For  Flag indicating that the area of the lot (taken from DTM) has changed by more than +/- 10% since the last version this should be its own report and process since it'll be useful for ZTLDB, PLUTO, and PAD updates

**Comment by SPTKL** [comment]
```
with dtm_compare as (
	SELECT bbl, geom_new, geom_old, 
		(case when geom_new = geom_old then 0 else 1 end) flag FROM 
	(select bbl, wkb_geometry as geom_new FROM dof_dtm."2019/09/03") a
	JOIN 
	(select bbl, wkb_geometry as geom_old from dof_dtm."2019/08/23") b
	USING(bbl))
, changed as (
Select *, (st_area(geom_new)-st_area(geom_old))/st_area(geom_old) as area_diff from dtm_compare
where flag = 1)
select * from changed where area_diff > 0.1 or area_diff < -0.1;
```
