### ISSUE TITLE
QAQC report: comparisons - Number of changes by type – ZD, CO, SD, other 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-zoningtaxlots#70]
How should the current "[All](https://edm-data-engineering.nycplanningdigital.com/?page=Zoning+Tax+Lots)" graph be modified?

**Comment by AmandaDoyle** [comment]
Group Zoning District, CO, SD, include everything else as an other

**Comment by SPTKL** [comment]
![image](https://user-images.githubusercontent.com/13207770/112496483-28bdcd80-8d5b-11eb-87ad-56ae0c49db4e.png)
pending improvement, the numbers are so different that they are not in the same scale, however, you can click on the lines to make them show/disappear, e.g
![image](https://user-images.githubusercontent.com/13207770/112496704-560a7b80-8d5b-11eb-9497-0662f19f56f6.png)
