### ISSUE TITLE
QAQC report: comparisons - Number of records with null values that were not null in the previous version 

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-zoningtaxlots#72]
How would this be different than Number of changes by type?  Would it be count of records where any field has a NULL value?
Brainstorm ideas on how to make sure NULLs are represented.
QAQC on fields that should never be NULL.

**Comment by SPTKL** [comment]
![image](https://user-images.githubusercontent.com/13207770/112496155-e3999b80-8d5a-11eb-8ea5-b6234852c45f.png)
added
