### ISSUE TITLE
QAQC: Report layout

### ISSUE THREAD

**Issue by AmandaDoyle** [NYCPlanning/db-zoningtaxlots#79]
Below lists the tables and charts that should be included in the updated QAQC page, and the order

- Total number of changed records (new) chart and table
- Total number of changes by borough (new)
- Number of changes by type (modified "All" graph) chart and table
- Version Comparison -- Null Count -- Number of records with null values that were not null in the previous version
- Number of BBLs added and removed chart and table
- Source Data Versions

**Comment by AmandaDoyle** [comment]
AD feedback

- Total number of changes by borough (new) - looks good
- Total BBL Pairwise Value Mismatch by Version - add blurb underneath describing the table.  I.e. "Total number of BBLs that have differing values between versions"
- BBL Pairwise Value Mismatch by Field Category - now I see why we charted the average difference.  Is there any way to configure the chart so that it's more readable?  Maybe each Category needs to be in it's own chart?
- BBLs added/removed - looks good
- I'm guessing "Shows how many records have non-null values..." is a placeholder

**Comment by AmandaDoyle** [comment]
AD feedback 03/28
 - Move BBL Pairwise NULL to Value and Value to NULL Counts below BBL Pairwise Value Mismatch by Field Category
- BBL Pairwise Value Mismatch by Field Category isn't usable.  You don't need to remove what's currently on the QAQC page so LS can see the issue, but can you provide an alternative (i.e. 4 separate charts, or go back to difference from average?)

**Comment by SPTKL** [comment]
@AmandaDoyle who's going to provide the manual review process?

**Comment by AmandaDoyle** [comment]
@SPTKL  LS will finalize the language, but you can start with what's outlined [here](https://github.com/NYCPlanning/db-zoningtaxlots/issues/75#issue-837855549)

**Comment by SPTKL** [comment]
I will add when the language is finalized

**Comment by SPTKL** [comment]
> BBL Pairwise Value Mismatch by Field Category isn't usable. You don't need to remove what's currently on the QAQC page so LS can see the issue, but can you provide an alternative (i.e. 4 separate charts, or go back to difference from average?)

note that switch back to the average will not fix this issue because it will just move the 0 line up, the order of magnitude of the plot will not change. I think it would be easier if the user just click through the legend. 

![image](https://user-images.githubusercontent.com/13207770/112847653-477ed580-9075-11eb-9189-1e4bcc858653.png)
![image](https://user-images.githubusercontent.com/13207770/112847678-4f3e7a00-9075-11eb-854b-8feac5e3e381.png)
